name: Despertador Automático Streamlit 4

on:
  schedule:
    # Se ejecuta cada 10 minutos
    - cron: '*/10 * * * *'
  workflow_dispatch: 

jobs:
  ping_job:
    runs-on: ubuntu-latest
    steps:
      - name: Enviando señal de vida mejorada
        run: |
          curl -I -s -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36" https://relojivaesv-jarj5p8m4ccorahaskc2l6.streamlit.app/
          echo "Ping enviado con éxito el $(date)"
